from app.domain.models import Role, RoleName


LEGAL_OS_PERMISSIONS = [
    "legal_os:read",
    "legal_os:write",
    "knowledge:read",
    "knowledge:write",
    "memory:read",
    "memory:write",
    "graph:read",
    "graph:write",
    "copilot:read",
    "marketplace:read",
    "marketplace:write",
    "latam:read",
    "latam:write",
    "agents:run",
]


ENTERPRISE_PERMISSIONS = [
    "enterprise:read",
    "enterprise:write",
    "organizations:read",
    "organizations:write",
    "data_platform:read",
    "data_platform:write",
    "orchestration:read",
    "orchestration:write",
    "ai_swarm:read",
    "ai_swarm:run",
    "telemetry:read",
    "revenue:read",
    "integrations:api",
    "governance:read",
    "governance:write",
    "cloud:read",
    "cloud:write",
]


ROLE_PERMISSIONS: dict[RoleName, list[str]] = {
    RoleName.super_admin: ["*"],
    RoleName.tenant_admin: [
        "users:read",
        "users:write",
        "roles:read",
        "clients:read",
        "clients:write",
        "cases:read",
        "cases:write",
        "cases:assign",
        "cases:change_status",
        "communications:read",
        "communications:write",
        "templates:write",
        "notifications:write",
        "ai:read",
        "ai:write",
        "ai:review",
        "intelligence:read",
        "intelligence:write",
        "dashboard:read",
        "warroom:read",
        "crm:read",
        "crm:write",
        "financial:read",
        "financial:write",
        "risk:read",
        "demo:write",
        "billing:read",
        "billing:write",
        "automation:read",
        "automation:write",
        "automation:run",
        "integrations:read",
        "integrations:write",
        "integrations:run",
        "audit:read",
    ]
    + LEGAL_OS_PERMISSIONS
    + ENTERPRISE_PERMISSIONS,
    RoleName.partner: [
        "users:read",
        "roles:read",
        "clients:read",
        "clients:write",
        "cases:read",
        "cases:write",
        "cases:assign",
        "cases:change_status",
        "communications:read",
        "communications:write",
        "templates:write",
        "notifications:write",
        "ai:read",
        "ai:write",
        "ai:review",
        "intelligence:read",
        "intelligence:write",
        "dashboard:read",
        "warroom:read",
        "crm:read",
        "crm:write",
        "financial:read",
        "financial:write",
        "risk:read",
        "demo:write",
        "billing:read",
        "billing:write",
        "automation:read",
        "automation:write",
        "automation:run",
        "integrations:read",
        "integrations:write",
        "integrations:run",
        "audit:read",
    ]
    + LEGAL_OS_PERMISSIONS
    + ENTERPRISE_PERMISSIONS,
    RoleName.lawyer: [
        "clients:read",
        "clients:write",
        "cases:read",
        "cases:write",
        "cases:change_status",
        "communications:read",
        "communications:write",
        "templates:write",
        "notifications:write",
        "ai:read",
        "ai:write",
        "ai:review",
        "intelligence:read",
        "intelligence:write",
        "dashboard:read",
        "warroom:read",
        "crm:read",
        "crm:write",
        "financial:read",
        "risk:read",
        "billing:read",
        "automation:read",
        "automation:write",
        "automation:run",
    ]
    + [
        "legal_os:read",
        "knowledge:read",
        "knowledge:write",
        "memory:read",
        "memory:write",
        "graph:read",
        "copilot:read",
        "marketplace:read",
        "latam:read",
        "agents:run",
        "enterprise:read",
        "organizations:read",
        "data_platform:read",
        "orchestration:read",
        "ai_swarm:read",
        "ai_swarm:run",
        "telemetry:read",
        "revenue:read",
        "integrations:api",
        "governance:read",
        "cloud:read",
    ],
    RoleName.assistant: [
        "clients:read",
        "clients:write",
        "cases:read",
        "cases:write",
        "communications:read",
        "communications:write",
        "automation:read",
        "automation:run",
        "legal_os:read",
        "knowledge:read",
        "memory:read",
        "graph:read",
        "marketplace:read",
        "latam:read",
        "enterprise:read",
        "data_platform:read",
        "telemetry:read",
        "governance:read",
    ],
    RoleName.client_user: ["clients:read", "cases:read"],
}


class RoleService:
    def list_roles(self) -> list[Role]:
        return [
            Role(name=name, permissions=permissions, description=f"LEXFLOW role: {name.value}")
            for name, permissions in ROLE_PERMISSIONS.items()
        ]

    def has_permission(self, role: RoleName, permission: str) -> bool:
        permissions = ROLE_PERMISSIONS[role]
        return "*" in permissions or permission in permissions


role_service = RoleService()
